<style>
.titulo {
  text-align: center;
}
.titulo h1 {
  color: #fca311;
  font-weight: 700;
  font-size: 50px;
  margin: 0;
  padding: 0;
  display: inline-block;
  position: relative;
}
.titulo h1::after {
  content: "";
  display: block;
  width: 100%;
  height: 5px;
  background-color: #4361ee;
  position: absolute;
  bottom: -10px;
  left: 0%;
}
</style>

<style>
.description {
    color: #4361ee;
    font-weight:300;
    font-size: 30px;
    text-align:center;
    justify-content: center;
    padding: 10px;
    margin: 0;
}
</style>

<div class="titulo">
  <h1>MindScope</h1>
  </style>
  <p class="description">LaborMarketTrends</p>
</div>

##### ***IMPORTAMOS LAS LIBRERÍAS***

In [1]:
# librerías para trabajar los Datasets.
import pandas as pd
import numpy as np

# Librerías para realizar gráficos.
import seaborn as sns
import matplotlib.pyplot as plt

##### ***CARGAMOS LA BASE DE DATOS***

In [2]:
df_gd = pd.read_csv("./datasets/glassdoor.csv")
df_gd_benefitscomments = pd.read_csv("./datasets/glassdoor_benefits_comments.csv")
df_gd_benefitshighlights = pd.read_csv("./datasets/glassdoor_benefits_highlights.csv")
df_gd_breadcrumbs = pd.read_csv("./datasets/glassdoor_breadCrumbs.csv")
df_gd_overviewcompetitors = pd.read_csv("./datasets/glassdoor_overview_competitors.csv")
df_gd_photos = pd.read_csv("./datasets/glassdoor_photos.csv")
df_gd_review = pd.read_csv("./datasets/glassdoor_reviews.csv")
df_gd_reviewresponses = pd.read_csv("./datasets/glassdoor_reviews_val_reviewResponses.csv")
df_gd_salaries = pd.read_csv("./datasets/glassdoor_salary_salaries.csv")
df_gd_wwfu = pd.read_csv("./datasets/glassdoor_wwfu.csv")
df_gd_wwfucaptions = pd.read_csv("./datasets/glassdoor_wwfu_val_captions.csv")
df_gd_wwfuphotos = pd.read_csv("./datasets/glassdoor_wwfu_val_photos.csv")
df_gd_wwfuvideos = pd.read_csv("./datasets/glassdoor_wwfu_val_videos.csv")
df_countrynames = pd.read_csv("./datasets/country_names_2_digit_codes.csv")
df_currencyexchange =  pd.read_csv("./datasets/currency_exchange.csv")

#### ***COMENZAMOS A TRABAJAR CON EL DATASET DE GLASSDOOR!***

In [3]:
# Establecemos esta linea para poder llegar a visualizar las 163 columnas...
pd.set_option('display.max_columns', None)

print("Tiene:", df_gd.shape[1], "columnas y", df_gd.shape[0], "filas")
df_gd.head(5)

Tiene: 163 columnas y 165290 filas

,benefits.benefitRatingDecimal,benefits.comments,benefits.highlights,benefits.numRatings,benefits.employerSummary,breadCrumbs,gaTrackerData.category,gaTrackerData.empId,gaTrackerData.empName,gaTrackerData.empSize,gaTrackerData.expired,gaTrackerData.industry,gaTrackerData.industryId,gaTrackerData.jobId.long,gaTrackerData.jobId.int,gaTrackerData.jobTitle,gaTrackerData.location,gaTrackerData.locationId,gaTrackerData.locationType,gaTrackerData.pageRequestGuid.guid,gaTrackerData.pageRequestGuid.guidValid,gaTrackerData.pageRequestGuid.part1,gaTrackerData.pageRequestGuid.part2,gaTrackerData.sector,gaTrackerData.sectorId,gaTrackerData.profileConversionTrackingParams.trackingCAT,gaTrackerData.profileConversionTrackingParams.trackingSRC,gaTrackerData.profileConversionTrackingParams.trackingXSP,gaTrackerData.jobViewTrackingResult.jobViewDisplayTimeMillis,gaTrackerData.jobViewTrackingResult.requiresTracking,gaTrackerData.jobViewTrackingResult.trackingUrl,header.adOrderId,header.advertiserType,header.applicationId,header.applyButtonDisabled,header.applyUrl,header.blur,header.coverPhoto,header.easyApply,header.employerId,header.employerName,header.expired,header.gocId,header.hideCEOInfo,header.jobTitle,header.locId,header.location,header.locationType,header.logo,header.logo2x,header.organic,header.overviewUrl,header.posted,header.rating,header.saved,header.savedJobId,header.sgocId,header.sponsored,header.userAdmin,header.uxApplyType,header.featuredVideo,header.normalizedJobTitle,header.urgencyLabel,header.urgencyLabelForMessage,header.urgencyMessage,header.needsCommission,header.payHigh,header.payLow,header.payMed,header.payPeriod,header.salaryHigh,header.salaryLow,header.salarySource,job.description,job.discoverDate,job.eolHashCode,job.importConfigId,job.jobReqId.long,job.jobReqId.int,job.jobSource,job.jobTitleId,job.listingId.long,job.listingId.int,map.country,map.employerName,map.lat,map.lng,map.location,map.address,map.postalCode,overview.allBenefitsLink,overview.allPhotosLink,overview.allReviewsLink,overview.allSalariesLink,overview.foundedYear,overview.hq,overview.industry,overview.industryId,overview.revenue,overview.sector,overview.sectorId,overview.size,overview.stock,overview.type,overview.description,overview.mission,overview.website,overview.allVideosLink,overview.competitors,overview.companyVideo,photos,rating.ceo.name,rating.ceo.photo,rating.ceo.photo2x,rating.ceo.ratingsCount,rating.ceoApproval,rating.recommendToFriend,rating.starRating,reviews,salary.country.cc3LetterISO,salary.country.ccISO,salary.country.continent.continentCode,salary.country.continent.continentName,salary.country.continent.id,salary.country.continent.new,salary.country.countryFIPS,salary.country.currency.currencyCode,salary.country.currency.defaultFractionDigits,salary.country.currency.displayName,salary.country.currency.id,salary.country.currency.name,salary.country.currency.negativeTemplate,salary.country.currency.new,salary.country.currency.positiveTemplate,salary.country.currency.symbol,salary.country.currencyCode,salary.country.defaultLocale,salary.country.defaultName,salary.country.defaultShortName,salary.country.employerSolutionsCountry,salary.country.id,salary.country.longName,salary.country.major,salary.country.name,salary.country.new,salary.country.population,salary.country.shortName,salary.country.tld,salary.country.type,salary.country.uniqueName,salary.country.usaCentricDisplayName,salary.currency.currencyCode,salary.currency.defaultFractionDigits,salary.currency.displayName,salary.currency.id,salary.currency.name,salary.currency.negativeTemplate,salary.currency.new,salary.currency.positiveTemplate,salary.currency.symbol,salary.lastSalaryDate,salary.salaries,wwfu
0,0.0,2801.0,2801.0,0,NaN,2801,-1,2183810,Modus Group,501-1000,False,Investment Banking & Asset Management,200053,3.227100e+09,NaN,Biogas Project Development Manager,Warsaw,3094484,CITY,0000016e56d0b5f2b16c3aea720c55ae,True,1573414548978,-5662085852901386834,Finance,10010,NaN,NaN,NaN,NaN,NaN,NaN,14295,GENERAL,0,False,/partner/jobListing.htm?pos=101&ao=14295&tgt=A...,True,/static/img/banners/default-ei-banner.jpg,True,2183810,Modus Group,False,-1,False,Biogas Project Development Manager,3094484,Warsaw,C,https://media.glassdoor.com/sqls/2183810/modus...,https://media.glassdoor.com/sqlm/2183810/modus...,True,/Overview/Working-at-Modus-Group-EI_IE2183810....,"Oct 24, 2019",-0.1,False,0,0,False,False,API,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,We are the drivers of the future who offer a g...,2019-10-24T04:52:23,-2041513,75613,4.101124e+09,NaN,WorkableHR.com,-1,3.227100e+09,NaN,Poland,Modus Group,52.2500,21.0000,Warsaw,NaN,NaN,/Benefits/Modus-Group-UK-Benefits-EI_IE2183810...,/Photos/Modus-Group-Office-Photos-E2183810.htm,/Reviews/Modus-Group-Reviews-E2183810.htm,/Salary/Modus-Group-Salaries-E2183810.htm,1993,"Vilnius, Lithuania",Investment Banking & Asset Management,200053,Unknown / Non-Applicable,Finance,10010,501 to 1000 employees,NaN,Company - Private,We are the drivers of the future who offer a g...,NaN,www.modus.group,NaN,NaN,NaN,1687.0,Liudas Liutkevičius,NaN,NaN,0.0,-0.1,-0.10,-0.1,2801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2483.0,NaN
1,4.0,2802.0,2802.0,3,NaN,2802,-1,10416,Boehringer Ingelheim,10000--1,False,Biotech & Pharmaceuticals,200021,3.406582e+09,NaN,Quality Manager - Boehringer Ingelheim Healthc...,NaN,3183562,CITY,0000016e56d0b5cfa19a4b2ba225a2ee,True,1573414548943,-6802041636413660434,Biotech & Pharmaceuticals,10005,NaN,NaN,NaN,NaN,NaN,NaN,43297,GENERAL,0,False,/partner/jobListing.htm?pos=101&ao=43297&s=58&...,True,/static/img/banners/default-ei-banner.jpg,False,10416,Boehringer Ingelheim,False,-1,False,Quality Manager - Boehringer Ingelheim Healthc...,3183562,Porto,C,https://media.glassdoor.com/sqls/10416/boehrin...,https://media.glassdoor.com/sqlm/10416/boehrin...,True,/Overview/Working-at-Boehringer-Ingelheim-EI_I...,"Nov 4, 2019",3.8,False,0,0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<strong></strong>\n<br/><br/>\n<strong></stron...,2019-11-04T03:59:14,320139505,91874,4.202175e+09,NaN,taleo,-1,3.406582e+09,NaN,NaN,Boehringer Ingelheim,41.1500,-8.6167,Porto,NaN,NaN,/Benefits/Boehringer-Ingelheim-UK-Benefits-EI_...,/Photos/Boehringer-Ingelheim-Office-Photos-E10...,/Reviews/Boehringer-Ingelheim-Reviews-E10416.htm,/Salary/Boehringer-Ingelheim-Salaries-E10416.htm,1885,"Ingelheim am Rhein, Germany",Biotech & Pharmaceuticals,200021,£5 to £10 billion (GBP),Biotech & Pharmaceuticals,10005,10000+ employees,NaN,Company - Private,NaN,NaN,www.boehringer-ingelheim.com,NaN,NaN,NaN,1688.0,Hubertus von Baumbach,NaN,NaN,123.0,0.8,0.76,3.8,2802,GBR,GB,EU,Europe,4.0,False,UK,GBP,2.0,United Kingdom Pound (GBP),2.0,United Kingdom Pound,$(#),False,$#,&pound;,GBP,en_UK,United Kingdom,United Kingdom,True,2.0,United Kingdom,True,United Kingdom,False,60363602.0,UK,.uk,N,United Kingdom,United Kingdom,GBP,2.0,United Kingdom Pound (GBP),2.0,United Kingdom Pound,$(#),False,$#,&pound;,2019-10-14T06:05:58,2484.0,NaN
2,0.0,2803.0,2803.0,0,NaN,2803,-1,1043373,Immobiliare.it,201-500,False,NaN,0,3.230738e+09,NaN,"Senior Software Engineer (PHP, Elixir, Python)",Milano,2802090,CITY,0000016e56d0b5c58f39733898e10986,True,1573414548933,-8126337365693101690,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,437149,GENERAL,0,False,/partner/jobListing.htm?pos=101&ao=437149&s=58...,True,/static/img/banners/default-ei-banner.jpg,False,1043373,Immobiliare.it,False,-1,False,"Senior Software Engineer (PHP, Elixir, Python)",2802090,Milan,C,https://media.glassdoor.com/sqls/1043373/immob...,https://media.glassdoor.com/sqlm/1043373/immob...,True,/Overview/Working-at-Immobiliare-it-EI_IE10433...,"Oct 28, 2019",2.4,False,0,0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dottori.it &egrave; il motore di ricerca che t...,2019-10-28T12:48:55,-1836661938,252306,4.069122e+09,NaN,Indeed XML Feed Employer,-1,3.230738e+09,NaN,Italy,Immobiliare.it,45.4667,9.2000,Milan,NaN,NaN,/Benefits/Immobiliare-it-UK-Benefits-EI_IE1043...,/Photos/Immobiliare-it-Office-Photos-E1043373.htm,/Reviews/Immobiliare-it-Reviews-E1043373.htm,/Salary/Immobiliare-it-Salaries-E1043373.htm,0,"MILANO, Italy",NaN,0,£25 to £50 million (GBP),NaN,0,201 to 500 employees,NaN,Company - Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-1.0,0.47,2.4,2803,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2485.0,NaN
3,0.0,2804.0,2804.0,0,NaN,2804,-1,2226886,Codup,1-50,False,NaN,0,3.406677e+09,NaN,Senior SQA Engineer,Karachi,3212296,CITY,0000016e56d0b5bca1733da6de4f4098,True,1573414548924,-6813034024377827176,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,389273,JOB_BOARD,0,False,/partner/jobListing.htm?pos=101&ao=389273&s=58...,True,/static/img/banners/default-ei-banner.jpg,False,2226886,Codup,False,-1,False,Senior SQA Engineer,3212296,Karāchi,C,NaN,NaN,False,"/Overview/Working-at-Codup-EI_IE2226886.11,16.htm","Nov 4, 2019",1.5,False,0,0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Codup is looking for a Senior SQA Engineer for...,2019-11-04T07:00:20,776027520,277822,4.202320e+09,NaN,Indeed XML Feed Dradis,35043,3.406677e+09,NaN,PK,Codup,24.8667,67.0500,Karāchi,NaN,NaN,"/Benefits/Codup-UK-Benefits-EI_IE2226886.0,5_I...",/Photos/Codup-Office-Photos-E2226886.htm,/Reviews/Codup-Reviews-E2226886.htm,/Salary/Codup-Salaries-E2226886.htm,0,"Karachi, Pakistan",NaN,0,Unknown / Non-Applicable,NaN,0,1 to 50 employees,NaN,Company - Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-1.0,0.00,1.5,2804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2486.0,NaN
4,0.0,2805.0,2805.0,0,NaN,2805,-1,851555,Markelytics Solutions,201-500,False,Consulting,200028,3.201516e+09,NaN,Research Manager,Bengaluru,2940587,CITY,0000016e56d0b5ba9a6c4efc3844657c,True,1573414548922,-7319388449201166980,Business Services,10006,NaN,NaN,NaN,NaN,NaN,NaN,437149,GENERAL,0,False,/partner/jobListing.htm?pos=101&ao=437149&s=58...,True,/static/img/banners/default-ei-banner.jpg,False,851555,MARKELYTICS SOLUTIONS INDIA,False,-1,False,Research Manager,2940587,Bengaluru,C,https://media.glassdoor.com/sqls/851555/markel...,https://media.glassdoor.com/sqlm/851555/markel...,True,/Overview/Working-at-MARKELYTICS-SOLUTIONS-IND...,"Nov 1, 2019",3.5,False,0,0,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<strong>Department:</strong> Research &amp; Op...,2019-11-01T13:40:48,928824553,252303,4.042579e+09,NaN,Indeed XML Feed Employer,33240,3.201516e+09,NaN,IN,Markelytics Solutions,12.9670,77.5873,Bengaluru,NaN,NaN,/Benefits/Markelytics-Solutions-UK-Benefits-EI...,/Photos/Markelytics-Solutions-Office-Photos-E8...,/Reviews/Markelytics-Solutions-Reviews-E851555...,/Salary/Markelytics-Solutions-Salaries-E851555...,2003,"Bangalore, India",Consulting,200028,Unknown / Non-Applicable,Business Services,10006,201 to 500 employees,NaN,Company - Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,-1.0,0.67,3.5,2805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2487.0,NaN

#### ***DESCRIPCIÓN BREVE DE LAS COLUMNAS***

- ***benefits.benefitRatingDecimal:*** una calificación numérica del paquete de beneficios de la empresa. ✗
- ***benefits.comments:*** comentarios de los empleados sobre los beneficios de la empresa. ✗
- ***benefits.highlights:*** destacados de los beneficios ofrecidos por la empresa. ✗
- ***benefits.numRatings:*** el número de calificaciones de beneficios que tiene la empresa. ✗
- ***benefits.employerSummary:*** un resumen proporcionado por el empleador sobre los beneficios que ofrece. ✗
- ***breadCrumbs:*** migas de pan que indican la ubicación del trabajo en el sitio web de Glassdoor. ✓
- ***gaTrackerData.category:*** la categoría a la que pertenece el trabajo según Glassdoor. ✗
- ***gaTrackerData.empId:*** el ID del empleador que publicó el trabajo. ✓
- ***gaTrackerData.empName:*** el nombre del empleador que publicó el trabajo. ✓
- ***gaTrackerData.empSize:*** el tamaño de la empresa en función del número de empleados. ✓
- ***gaTrackerData.expired:*** indica si el trabajo ha caducado. ✓
- ***gaTrackerData.industry:*** la industria a la que pertenece la empresa. ✓ 
- ***gaTrackerData.industryId:*** el ID de la industria a la que pertenece la empresa. ✓
- ***gaTrackerData.jobId.long:*** un ID único y largo asignado por Glassdoor al trabajo. ✗
- ***gaTrackerData.jobId.int:*** un ID numérico asignado por Glassdoor al trabajo. ✗ 
- ***gaTrackerData.jobTitle:*** el título del trabajo. ✓ 
- ***gaTrackerData.location:*** la ubicación del trabajo. ✗
- ***gaTrackerData.locationId:*** el ID de la ubicación del trabajo. ✓ 
- ***gaTrackerData.locationType:*** el tipo de ubicación del trabajo (por ejemplo, ciudad, estado, país). ✗
- ***gaTrackerData.pageRequestGuid.guid:*** un identificador único para la solicitud de página. ✗
- ***gaTrackerData.pageRequestGuid.guidValid:*** indica si el identificador único es válido. ✗
- ***gaTrackerData.pageRequestGuid.part1:*** la primera parte del identificador único. ✗
- ***gaTrackerData.pageRequestGuid.part2:*** la segunda parte del identificador único. ✗
- ***gaTrackerData.sector:*** el sector al que pertenece la empresa. ✓
- ***gaTrackerData.sectorId:*** el ID del sector al que pertenece la empresa. ✓
- ***gaTrackerData.profileConversionTrackingParams.trackingCAT:*** un parámetro de seguimiento de conversión. ✗
- ***gaTrackerData.profileConversionTrackingParams.trackingSRC:*** otro parámetro de seguimiento de conversión. ✗
- ***gaTrackerData.profileConversionTrackingParams.trackingXSP:*** otro parámetro de seguimiento de conversión. ✗
- ***gaTrackerData.jobViewTrackingResult.jobViewDisplayTimeMillis:*** el tiempo que se muestra el trabajo en milisegundos. ✗
- ***gaTrackerData.jobViewTrackingResult.requiresTracking:*** indica si se requiere seguimiento. ✗
- ***gaTrackerData.jobViewTrackingResult.trackingUrl:*** la URL de seguimiento. ✗
- ***header.adOrderId:*** el ID del anuncio. ✗
- ***header.advertiserType:*** el tipo de anunciante. ✗
- ***header.applicationId:*** el ID de la aplicación. ✗
- ***header.applyButtonDisabled:*** indica si el botón de solicitud está deshabilitado. ✗
- ***header.applyUrl:*** la URL de solicitud de trabajo. ✗
- ***header.blur:*** una imagen borrosa del logotipo de la empresa. ✗
- ***header.coverPhoto:*** una foto de portada de la empresa. ✗
- ***header.easyApply:*** indica si el proceso de solicitud es fácil. ✗
- ***header.employerId:*** el ID del empleador. ✓
- ***header.employerName:*** el nombre del empleador. ✓
- ***header.expired:*** indica si la oferta de trabajo ha expirado o no. ✓
- ***header.gocId:*** el ID de la oferta de trabajo en Glassdoor. ✗
- ***header.hideCEOInfo:*** indica si la información del CEO de la empresa se oculta o no. ✗
- ***header.jobTitle:*** el título del trabajo. ✓
- ***header.locId:*** el ID de ubicación de Glassdoor de la ubicación del trabajo. ✓
- ***header.location:*** la ubicación del trabajo. ✓
- ***header.locationType:*** el tipo de ubicación (por ejemplo, "ciudad" o "país"). ✗
- ***header.logo:*** la URL del logotipo de la empresa. ✗
- ***header.logo2x:*** la URL del logotipo de la empresa en alta resolución. ✗
- ***header.organic:*** indica si la oferta de trabajo es orgánica o patrocinada. ✗
- ***header.overviewUrl:*** la URL de la página de descripción general de la empresa. ✗
- ***header.posted:*** la fecha en que se publicó la oferta de trabajo. ✓
- ***header.rating:*** la calificación general de la empresa en Glassdoor (1-5 estrellas). ✓
- ***header.saved:*** indica si el usuario ha guardado la oferta de trabajo en su cuenta de Glassdoor. ✗
- ***header.savedJobId:*** el ID de la oferta de trabajo guardada. ✗
- ***header.sgocId:*** el ID de la empresa en Glassdoor. ✗
- ***header.sponsored:*** indica si la oferta de trabajo es patrocinada o no. ✗
- ***header.userAdmin:*** indica si el usuario que vio la oferta de trabajo es un administrador de Glassdoor. ✗
- ***header.uxApplyType:*** el tipo de solicitud de trabajo (por ejemplo, "Fácil aplicación" o "Aplicar en el sitio web de la empresa"). ✗
- ***header.featuredVideo:*** indica si hay un video destacado en la página de descripción general de la empresa. ✗
- ***header.normalizedJobTitle:*** el título del trabajo normalizado. ✗
- ***header.urgencyLabel:*** una etiqueta que indica cuán urgente es llenar la posición (por ejemplo, "Contratación rápida"). ✗
- ***header.urgencyLabelForMessage:*** una versión abreviada de la etiqueta de urgencia. ✗
- ***header.urgencyMessage:*** un mensaje que indica cuán urgente es llenar la posición. ✗
- ***header.needsCommission:*** indica si el trabajo tiene comisiones asociadas. ✗
- ***header.payHigh:*** el salario máximo ofrecido para el trabajo. ✓
- ***header.payLow:*** el salario mínimo ofrecido para el trabajo. ✓
- ***header.payMed:*** el salario medio ofrecido para el trabajo. ✓
- ***header.payPeriod:*** el período de pago (por ejemplo, "por hora" o "anualmente"). ✓
- ***header.salaryHigh:*** el salario máximo reportado para el trabajo. ✓
- ***header.salaryLow:*** el salario mínimo reportado para el trabajo. ✗
- ***header.salarySource:*** la fuente de los datos salariales (por ejemplo, "Empleados actuales" o "Empleados anteriores"). ✗
- ***job.description:*** la descripción del trabajo. ✓
- ***job.discoverDate:*** la fecha en que Glassdoor descubrió la oferta de trabajo. ✗
- ***job.eolHashCode:*** un código hash que identifica la oferta de trabajo. ✗
- ***job.importConfigId:*** el ID de la configuración de importación de la oferta de trabajo. ✗
- ***job.jobReqId.long:*** el ID de requisito de trabajo de Glassdoor. ✗
- ***job.jobReqId.int:*** el ID de requisito de trabajo de Glassdoor en formato numérico. ✗
- ***job.jobSource:*** el origen del trabajo (p. ej., Glassdoor, LinkedIn, etc.). ✓
- ***job.jobTitleId:*** el ID del título del trabajo en Glassdoor en formato numérico. ✓
- ***job.listingId.long:*** el ID de listado del trabajo en Glassdoor en formato de número largo. ✗
- ***job.listingId.int:*** el ID de listado del trabajo en Glassdoor en formato numérico. ✗
- ***map.country:*** el país donde se encuentra la empresa. ✓
- ***map.employerName:*** el nombre de la empresa que figura en el mapa. ✓
- ***map.lat:*** la latitud de la ubicación de la empresa. ✓
- ***map.lng:*** la longitud de la ubicación de la empresa. ✓
- ***map.location:*** la dirección o ubicación de la empresa en formato de texto. ✓
- ***map.address:*** la dirección de la empresa en formato de texto. ✓
- ***map.postalCode:*** el código postal de la ubicación de la empresa. ✓
- ***overview.allBenefitsLink:*** el enlace a todos los beneficios ofrecidos por la empresa. ✗
- ***overview.allPhotosLink:*** el enlace a todas las fotos relacionadas con la empresa. ✗
- ***overview.allReviewsLink:*** el enlace a todas las revisiones de la empresa. ✗
- ***overview.allSalariesLink:*** el enlace a todos los salarios publicados por la empresa. ✗
- ***overview.foundedYear:*** el año en que la empresa fue fundada. ✓
- ***overview.hq:*** la sede de la empresa. ✗
- ***overview.industry:*** la industria en la que opera la empresa. ✓
- ***overview.industryId:*** el ID de la industria en la que opera la empresa en formato numérico. ✓
- ***overview.revenue:*** los ingresos anuales de la empresa. ✓
- ***overview.sector:*** el sector de la empresa. ✓
- ***overview.sectorId:*** el ID del sector de la empresa en formato numérico. ✓
- ***overview.size:*** el tamaño de la empresa en términos de empleados. ✓
- ***overview.stock:*** si la empresa cotiza en bolsa o no. ✗
- ***overview.type:*** el tipo de empresa (p. ej., pública, privada, sin fines de lucro, etc.). ✗
- ***overview.description:*** una descripción breve de la empresa. ✗
- ***overview.mission:*** la misión de la empresa. ✗
- ***overview.website:*** el sitio web de la empresa. ✗
- ***overview.allVideosLink:*** el enlace a todos los videos relacionados con la empresa.✗
- ***overview.competitors:*** una lista de los competidores de la empresa.  ✓
- ***overview.companyVideo:*** el video de presentación de la empresa. ✗
- ***photos:*** las fotos relacionadas con el trabajo o la empresa. ✗
- ***rating.ceo.name:*** el nombre del CEO de la empresa. ✗
- ***rating.ceo.photo:*** la foto del CEO de la empresa. ✗
- ***rating.ceo.photo2x:*** la foto del CEO de la empresa en alta resolución. ✗
- ***rating.ceo.ratingsCount:*** el número de calificaciones que ha recibido el CEO. ✗
- ***rating.ceoApproval:*** el porcentaje de aprobación del CEO por parte de los empleados.✗ 
- ***rating.recommendToFriend:*** el porcentaje de empleados que recomendarían la empresa a un amigo. ✗
- ***rating.starRating:*** la calificación de la empresa en una escala de 1 a 5 estrellas. ✓
- ***reviews:*** las revisiones de la empresa o del trabajo publicadas por los empleados o ex empleados. ✗
- ***salary.country.cc3LetterISO:*** el código ISO de 3 letras del país en el que se publica la información salarial. ✗
- ***salary.country.ccISO:*** el código ISO de 2 letras del país en el que se publica la información salarial. ✓
- ***salary.country.continent.continentCode:*** el código del continente en el que se encuentra el país en el que se publica la información salarial. ✗ 
- ***salary.country.continent.continentName:*** el nombre del continente en el que se encuentra el país en el que se publica la información salarial. ✗ 
- ***salary.country.continent.id:*** el ID del continente en el que se encuentra el país en el que se publica la información salarial. ✗
- ***salary.country.continent.new:*** una marca booleana que indica si el continente es nuevo o no. ✗
- ***salary.country.countryFIPS:*** el código FIPS del país en el que se publica la información salarial. ✗
- ***salary.country.currency.currencyCode:*** el código de la moneda utilizada en el país en el que se publica la información salarial. ✗
- ***salary.country.currency.defaultFractionDigits:*** la cantidad de decimales que se utilizan para la moneda utilizada en el país en el que se publica la información salarial. ✗
- ***salary.country.currency.displayName:*** el nombre completo de la moneda utilizada en el país en el que se publica la información salarial. ✓
- ***salary.country.currency.id:*** el ID de la moneda utilizada en el país en el que se publica la información salarial. ✗
- ***salary.country.currency.name:*** el nombre de la moneda utilizada en el país en el que se publica la información salarial. ✗
- ***salary.country.currency.negativeTemplate:*** el formato utilizado para mostrar cantidades negativas en la moneda utilizada en el país en el que se publica la información salarial. ✗
- ***salary.country.currency.new:*** una marca booleana que indica si la moneda es nueva o no. ✗
- ***salary.country.currency.positiveTemplate:*** el formato utilizado para mostrar cantidades positivas en la moneda utilizada en el país en el que se publica la información salarial. ✗
- ***salary.country.currency.symbol:*** el símbolo utilizado para representar la moneda utilizada en el país en el que se publica la información salarial. ✗
- ***salary.country.currencyCode:*** el código de la moneda utilizada en el país en el que se publica la información salarial. ✗
- ***salary.country.defaultLocale:*** el código del idioma utilizado en el país en el que se publica la información salarial. ✗
- ***salary.country.defaultName:*** el nombre del país en el que se publica la información salarial. ✗
- ***salary.country.defaultShortName:*** el nombre corto del país en el que se publica la información salarial. ✗
- ***salary.country.employerSolutionsCountry:*** una marca booleana que indica si el país es un "país de soluciones para empleadores". ✗
- ***salary.country.id:*** el ID del país en el que se publica la información salarial. ✗
- ***salary.country.longName:*** el nombre completo del país en el que se publica la información salarial. ✗
- ***salary.country.major:*** una marca booleana que indica si el país es un "país principal" o no. ✗
- ***salary.country.name:*** el nombre del país en el que se publica la información salarial. ✗
- ***salary.country.new:*** una marca booleana que indica si el país es nuevo o no. ✗
- ***salary.country.population:*** la población del país del salario. ✗
- ***salary.country.shortName:*** el nombre corto del país del salario. ✗
- ***salary.country.tld:*** el dominio de nivel superior (TLD) del país del salario. ✗
- ***salary.country.type:*** el tipo de país del salario. ✗
- ***salary.country.uniqueName:*** el nombre único del país del salario. ✗
- ***salary.country.usaCentricDisplayName:*** el nombre del país del salario centrado en EE. UU. ✗
- ***salary.currency.currencyCode:*** el código de la moneda del salario. ✗
- ***salary.currency.defaultFractionDigits:*** la cantidad de dígitos decimales por defecto para la moneda del salario. ✗
- ***salary.currency.displayName:*** el nombre completo de la moneda del salario. ✗
- ***salary.currency.id:*** el identificador único de la moneda del salario. ✗
- ***salary.currency.name:*** el nombre de la moneda del salario. ✗ 
- ***salary.currency.negativeTemplate:*** la plantilla para representar un número negativo en la moneda del salario. ✗
- ***salary.currency.positiveTemplate:*** la plantilla para representar un número positivo en la moneda del salario. ✗
- ***salary.currency.symbol:*** el símbolo de la moneda del salario. ✗
- ***salary.lastSalaryDate:*** la fecha en la que se actualizó por última vez el salario. ✗
- ***salary.salaries:*** la información del salario para este trabajo en particular.  ✗ 
- ***wwfu:*** un valor booleano que indica si la empresa está en el programa de Friendly Work Environment de Glassdoor. ✓

In [4]:
# Seleccionamos las columnas relevantes.
df_gd = df_gd[["gaTrackerData.empId",
               "gaTrackerData.empName",
               "gaTrackerData.empSize",
               "gaTrackerData.expired",
               "gaTrackerData.industry",
               "gaTrackerData.industryId",
               "gaTrackerData.jobTitle",
               "gaTrackerData.locationId",
               "gaTrackerData.sector",
               "gaTrackerData.sectorId",
               "header.employerId",
               "header.employerName",
               "header.expired",
               "header.jobTitle",
               "header.locId",
               "header.location",
               "header.posted",
               "header.rating",
               "header.payHigh",
               "header.payLow",
               "header.payMed",
               "header.payPeriod",
               "header.salaryHigh",
               "job.description",
               "job.jobSource",
               "job.jobTitleId",
               "map.country",
               "map.employerName",
               "map.lat",
               "map.lng",
               "map.location",
               "map.address",
               "map.postalCode",
               "overview.foundedYear",
               "overview.industry",
               "overview.industryId",
               "overview.revenue",
               "overview.sector",
               "overview.sectorId",
               "overview.size",
               "overview.competitors",
               "rating.starRating",
               "salary.country.cc3LetterISO",
               "salary.country.currency.displayName",
               "wwfu",
               "breadCrumbs"]]

In [5]:
# Funcion para comparar dos columnas del dataset, y devolver un mensaje si son diferentes.
def comparar_columnas(df, col1, col2):    
    if df[col1].equals(df[col2]):
        return f"Las columnas '{col1}' y '{col2}' son iguales."
    else:
        num_diferencias = sum(df[col1] != df[col2])
        return f"Las columnas '{col1}' y '{col2}' son diferentes. Hay {num_diferencias} valores diferentes."
 

def unir_columnas(df, col1, col2, nueva_col):
    # Comprobar que las columnas son iguales
    if not df[col1].equals(df[col2]):
        print(f"Error: las columnas '{col1}' y '{col2}' no son iguales.")
        return df
    # Crear una nueva columna con la concatenación de las dos columnas iguales
    df[nueva_col] = df[col1]
    # Eliminar las columnas originales del DataFrame
    df = df.drop(columns=[col1, col2])
    return df

def unir_columnas_y_reemplazar_nulos(df, col1, col2, nueva_col):
    # Concatenar las dos columnas
    df[nueva_col] = df[col1].fillna(df[col2])
    # Eliminar las columnas originales del DataFrame
    df = df.drop(columns=[col1, col2])
    return df

In [6]:
print(comparar_columnas(df_gd, "gaTrackerData.empId", "header.employerId"))
print(df_gd["gaTrackerData.empId"].unique())
print(df_gd["header.employerId"].unique())

Las columnas 'gaTrackerData.empId' y 'header.employerId' son diferentes. Hay 68 valores diferentes.
[2183810   10416 1043373 ...  841936  749518  417044]
[2183810   10416 1043373 ...  841936  749518  417044]

In [7]:
print(comparar_columnas(df_gd, "gaTrackerData.empName", "header.employerName"))
print("")
print(df_gd["gaTrackerData.empName"].unique())
print("")
print(df_gd["header.employerName"].unique())

Las columnas 'gaTrackerData.empName' y 'header.employerName' son diferentes. Hay 64894 valores diferentes.

['Modus Group' 'Boehringer Ingelheim' 'Immobiliare.it ' ...
 'New Channel International Education Group'
 'Nuclear Waste Management Organization'
 'Translational Research in Oncology']

['Modus Group' 'Boehringer Ingelheim' 'Immobiliare.it' ...
 'WNS Global Services SA' 'Simatelex' 'DATAIKU']

In [8]:
print(comparar_columnas(df_gd, "header.employerName", "map.employerName"))
print("")
print(df_gd["header.employerName"].unique())
print("")
print(df_gd["map.employerName"].unique())

Las columnas 'header.employerName' y 'map.employerName' son diferentes. Hay 64826 valores diferentes.

['Modus Group' 'Boehringer Ingelheim' 'Immobiliare.it' ...
 'WNS Global Services SA' 'Simatelex' 'DATAIKU']

['Modus Group' 'Boehringer Ingelheim' 'Immobiliare.it ' ...
 'New Channel International Education Group'
 'Nuclear Waste Management Organization'
 'Translational Research in Oncology']

In [9]:
print(comparar_columnas(df_gd, "gaTrackerData.empName", "map.employerName"))
print("")
print(df_gd["gaTrackerData.empName"].unique())
print("")
print(df_gd["map.employerName"].unique())

Las columnas 'gaTrackerData.empName' y 'map.employerName' son diferentes. Hay 18209 valores diferentes.

['Modus Group' 'Boehringer Ingelheim' 'Immobiliare.it ' ...
 'New Channel International Education Group'
 'Nuclear Waste Management Organization'
 'Translational Research in Oncology']

['Modus Group' 'Boehringer Ingelheim' 'Immobiliare.it ' ...
 'New Channel International Education Group'
 'Nuclear Waste Management Organization'
 'Translational Research in Oncology']

In [10]:
print(comparar_columnas(df_gd, "gaTrackerData.empSize", "overview.size"))
print("")
print(df_gd["gaTrackerData.empSize"].unique())
print("")
print(df_gd["overview.size"].unique())

Las columnas 'gaTrackerData.empSize' y 'overview.size' son diferentes. Hay 165290 valores diferentes.

['501-1000' '10000--1' '201-500' '1-50' '51-200' '1001-5000' nan '-1-0'
 '5001-10000']

['501 to 1000 employees' '10000+ employees' '201 to 500 employees'
 '1 to 50 employees' '51 to 200 employees' '1001 to 5000 employees' nan
 'Unknown' '5001 to 10000 employees']

In [11]:
print(comparar_columnas(df_gd, "gaTrackerData.expired", "header.expired"))
print(df_gd["gaTrackerData.expired"].unique())
print(df_gd["header.expired"].unique())

Las columnas 'gaTrackerData.expired' y 'header.expired' son diferentes. Hay 149 valores diferentes.
[False  True]
[False  True]

In [12]:
print(comparar_columnas(df_gd, "gaTrackerData.industry", "overview.industry"))
print("")
print(df_gd["gaTrackerData.industry"].unique())
print("")
print(df_gd["overview.industry"].unique())

Las columnas 'gaTrackerData.industry' y 'overview.industry' son diferentes. Hay 64022 valores diferentes.

['Investment Banking & Asset Management' 'Biotech & Pharmaceuticals' nan
 'Consulting' 'Computer Hardware & Software' 'Staffing & Outsourcing'
 'Internet' 'Accounting' 'Banks & Credit Unions'
 'Health Care Products Manufacturing' 'Building & Personnel Services'
 'Industrial Manufacturing' 'Consumer Electronics & Appliances Stores'
 'IT Services' 'Financial Transaction Processing'
 'Electrical & Electronic Manufacturing' 'Telecommunications Services'
 'Food & Beverage Manufacturing' 'Advertising & Marketing'
 'Consumer Products Manufacturing' 'Energy' 'Commercial Equipment Rental'
 'Social Assistance' 'Home Furniture & Housewares Stores'
 'Enterprise Software & Network Solutions' 'Express Delivery Services'
 'Miscellaneous Manufacturing' 'Oil & Gas Exploration & Production'
 'Federal Agencies' 'Lending' 'Oil & Gas Services' 'Construction'
 'Insurance Agencies & Brokerages' 'Video Games' 'Brokerage Services'
 'Transportation Equipment Manufacturing' 'Colleges & Universities'
 'Other Retail Stores' 'Sporting Goods Stores' 'Publishing'
 'Automotive Parts & Accessories Stores'
 'Department, Clothing, & Shoe Stores' 'Research & Development'
 'Aerospace & Defense' 'Chemical Manufacturing' 'Insurance Carriers'
 'Health Care Services & Hospitals' 'General Repair & Maintenance'
 'Food Production' 'Motion Picture Production & Distribution'
 'Financial Analytics & Research' 'Cable, Internet & Telephone Providers'
 'Transportation Management' 'Farm Support Services'
 'TV Broadcast & Cable Networks' 'Real Estate'
 'Education Training Services' 'Metal & Mineral Manufacturing'
 'Travel Agencies' 'Airlines' 'Architectural & Engineering Services'
 'Stock Exchanges' 'Logistics & Supply Chain'
 'General Merchandise & Superstores' 'Gambling' 'Security Services'
 'Legal' 'Grocery Stores & Supermarkets' 'Utilities'
 'Food & Beverage Stores' 'Animal Production'
 'Commercial Equipment Repair & Maintenance' 'Consumer Product Rental'
 'Hotels, Motels, & Resorts' 'Beauty & Personal Accessories Stores'
 'Wholesale' 'Bus Transportation Services'
 'Telecommunications Manufacturing' 'Commercial Printing'
 'Casual Restaurants' 'Shipping' 'Health Fundraising Organizations'
 'Health, Beauty, & Fitness' 'Music Production & Distribution'
 'Venture Capital & Private Equity' 'Cruise Ships'
 'Membership Organizations' 'Passenger Rail' 'Photography' 'Mining'
 'Catering & Food Service Contractors' 'Museums, Zoos & Amusement Parks'
 'State & Regional Agencies' 'Vehicle Dealers'
 'Media & Entertainment Retail Stores' 'Home Centers & Hardware Stores'
 'Car Rental' 'News Outlet' 'Performing Arts' 'Charter Air Travel'
 'Wood Product Manufacturing' 'Pet & Pet Supplies Stores'
 'Fast-Food & Quick-Service Restaurants' 'Asphalt Products Manufacturing'
 'Drug & Health Stores' 'K-12 Education' 'Audiovisual'
 'Religious Organizations' 'Metals Brokers' 'Auto Repair & Maintenance'
 'Sports & Recreation' 'Timber Operations' 'Gas Stations'
 'Towing Services' 'Convenience Stores & Truck Stops' 'Rail' 'Trucking'
 'Talent & Modeling Agencies' 'Preschool & Child Care'
 'Gift, Novelty & Souvenir Stores' 'Moving Services'
 'Business Service Centers & Copy Shops' 'Self-Storage Services '
 'Municipal Governments' 'Camping & RV Parks' 'Grantmaking Foundations'
 'Ticket Sales' 'Upscale Restaurants' 'Office Supply Stores'
 'Parking Lots & Garages' 'Adult Entertainment' 'Movie Theaters'
 'Funeral Services' 'Radio' 'Taxi & Limousine Services'
 'Veterinary Services' 'Auctions & Galleries' 'Truck Rental & Leasing']

['Investment Banking & Asset Management' 'Biotech & Pharmaceuticals' nan
 'Consulting' 'Computer Hardware & Software' 'Staffing & Outsourcing'
 'Internet' 'Accounting' 'Banks & Building Societies'
 'Healthcare Product Manufacturing' 'Building & Personnel Services'
 'Industrial Manufacturing' 'Consumer Electronics & Appliance Shops'
 'IT Services' 'Financial Transaction Processing'
 'Electrical & Electronic Manufacturing' 'Telecommunications Services'
 'Food & Drink Manufacturing' 'Advertising & Marketing'
 'Consumer Products Manufacturing' 'Energy' 'Commercial Equipment Hire'
 'Social Services' 'Home Furniture and Houseware Shops'
 'Enterprise Software & Network Solutions' 'Express Delivery Services'
 'Miscellaneous Manufacturing' 'Oil & Gas Exploration & Production'
 'Government Agencies' 'Lending' 'Oil & Gas Services'
 'Building & Construction' 'Insurance Agencies & Brokerages' 'Video Games'
 'Brokerage Services' 'Transportation Equipment Manufacturing'
 'Colleges & Universities' 'Other Retail Shops' 'Sporting Goods Shops'
 'Publishing' 'Motor Vehicle Parts & Accessories Shops'
 'Department, Clothing, & Shoe Shops' 'Research & Development'
 'Aerospace & Defence' 'Chemical Manufacturing' 'Insurance Operators'
 'Healthcare Services & Hospitals' 'General Repair & Maintenance'
 'Food Production' 'Film Production & Distribution'
 'Financial Analytics & Research' 'Cable, Internet & Telephone Providers'
 'Transportation Management' 'Farm Support Services'
 'TV Broadcasting & Cable Networks' 'Estate Agents'
 'Education Training Services' 'Metal & Mineral Manufacturing'
 'Travel Agencies' 'Airlines' 'Architectural & Engineering Services'
 'Stock Exchanges' 'Logistics & Supply Chain'
 'General Merchandise & Superstores' 'Gambling' 'Security Services'
 'Legal' 'Grocery Shops & Supermarkets' 'Utilities'
 'Food & Beverage Shops' 'Animal Production'
 'Commercial Equipment Repair & Maintenance' 'Consumer Product Hire'
 'Hotel & Resorts' 'Beauty & Personal Accessories Shops' 'Wholesale'
 'Bus & Coach Services' 'Telecommunications Manufacturing'
 'Commercial Printing' 'Casual Restaurants' 'Shipping' 'Health Charities'
 'Health, Beauty & Fitness' 'Music Production & Distribution'
 'Venture Capital & Private Equity' 'Cruise Ships'
 'Membership Organisations' 'Passenger Rail' 'Photography' 'Mining'
 'Catering & Food Service Contractors' 'Museums, Zoos & Amusement Parks'
 'Regional & County Councils' 'Vehicle Dealers'
 'Media & Entertainment Retail Shops' 'Home Centres & DIY/Hardware Shops'
 'Car Hire' 'News Outlets' 'Performing Arts' 'Charter Air Travel'
 'Wood Product Manufacturing' 'Pet & Pet Supply Shops'
 'Fast-Food & Quick-Service Restaurants' 'Asphalt Product Manufacturing'
 'Pharmacies & Health Shops' 'Primary & Secondary Education'
 'Audio/Visual' 'Religious Organisations' 'Metal Brokerages'
 'Vehicle Repair & Maintenance' 'Sports & Recreation' 'Timber Operations'
 'Petrol Stations' 'Towing Services'
 'Convenience Stores & Roadside Services' 'Rail Freight' 'Haulage'
 'Talent & Modelling Agencies' 'Preschool & Child Care'
 'Gift, Novelty & Souvenir Shops' 'Removal Services'
 'Business Service Centres & Copy Shops' 'Self-Storage Services'
 'Local Councils' 'Camping & Caravan Parks' 'Charitable Foundations'
 'Ticket Sales' 'Up-Market Restaurants' 'Office Supply Shops' 'Car Parks'
 'Adult Entertainment' 'Cinemas' 'Funeral Services' 'Radio'
 'Taxi Services' 'Veterinary Services' 'Auctions & Galleries'
 'Lorry Hire & Leasing']

In [13]:
print(comparar_columnas(df_gd, "gaTrackerData.industryId", "overview.industryId"))
print("")
print(df_gd["gaTrackerData.industryId"].unique())
print("")
print(df_gd["overview.industryId"].unique())

Las columnas 'gaTrackerData.industryId' y 'overview.industryId' son iguales.

[200053 200021      0 200028 200060 200032 200063 200001 200048 200072
 200024 200073 200103 200064 200052 200070 200122 200071 200022 200069
 200090 200026 200089 200112 200061 200124 200147 200091 200056 200054
 200092 200036 200065 200083 200049 200075 200044 200115 200117 200080
 200101 200105 200030 200003 200068 200066 200059 200037 200008 200077
 200051 200120 200131 200006 200082 200094 200045 200074 200144 200134
 200023 200055 200125 200109 200013 200031 200002 200145 200093 200107
 200004 200035 200038 200140 200102 200033 200135 200121 200027 200095
 200129 200087 200040 200078 200146 200139 200029 200141 200017 200085
 200096 200015 200058 200119 200113 200111 200137 200079 200016 200138
 200076 200116 200098 200067 200123 200106 200046 200011 200088 200084
 200034 200018 200009 200108 200130 200097 200128 200133 200019 200047
 200110 200126 200025 200042 200057 200136 200086 200020 200099 200114
 200127 200010 200014 200039 200081 200143 200043 200100 200132]

[200053 200021      0 200028 200060 200032 200063 200001 200048 200072
 200024 200073 200103 200064 200052 200070 200122 200071 200022 200069
 200090 200026 200089 200112 200061 200124 200147 200091 200056 200054
 200092 200036 200065 200083 200049 200075 200044 200115 200117 200080
 200101 200105 200030 200003 200068 200066 200059 200037 200008 200077
 200051 200120 200131 200006 200082 200094 200045 200074 200144 200134
 200023 200055 200125 200109 200013 200031 200002 200145 200093 200107
 200004 200035 200038 200140 200102 200033 200135 200121 200027 200095
 200129 200087 200040 200078 200146 200139 200029 200141 200017 200085
 200096 200015 200058 200119 200113 200111 200137 200079 200016 200138
 200076 200116 200098 200067 200123 200106 200046 200011 200088 200084
 200034 200018 200009 200108 200130 200097 200128 200133 200019 200047
 200110 200126 200025 200042 200057 200136 200086 200020 200099 200114
 200127 200010 200014 200039 200081 200143 200043 200100 200132]

In [14]:
print(comparar_columnas(df_gd, "gaTrackerData.jobTitle", "header.jobTitle"))
print("")
print(df_gd["gaTrackerData.jobTitle"].unique())
print("")
print(df_gd["header.jobTitle"].unique())

Las columnas 'gaTrackerData.jobTitle' y 'header.jobTitle' son iguales.

['Biogas Project Development Manager'
 'Quality Manager - Boehringer Ingelheim Healthcare Portugal'
 'Senior Software Engineer (PHP, Elixir, Python)' ...
 'Software Development Engineer (C/C++) m/f'
 'Deputy Project Manager, Manager Quality Control, Area Engineers Structure/Equipments/Process Piping/Electrical/Instrumentation, Incharge Stores and Millwrights / Fitters / Welders'
 'BIO MASS SCIENTIST / RESEARCHERS']

['Biogas Project Development Manager'
 'Quality Manager - Boehringer Ingelheim Healthcare Portugal'
 'Senior Software Engineer (PHP, Elixir, Python)' ...
 'Software Development Engineer (C/C++) m/f'
 'Deputy Project Manager, Manager Quality Control, Area Engineers Structure/Equipments/Process Piping/Electrical/Instrumentation, Incharge Stores and Millwrights / Fitters / Welders'
 'BIO MASS SCIENTIST / RESEARCHERS']

In [15]:
print(comparar_columnas(df_gd, "map.location", "header.location"))
print("")
print(df_gd["map.location"].unique())
print("")
print(df_gd["header.location"].unique())

Las columnas 'map.location' y 'header.location' son iguales.

['Warsaw' 'Porto' 'Milan' ... 'Tholen' 'Hsinchu, Taiwan' 'Berneck']

['Warsaw' 'Porto' 'Milan' ... 'Tholen' 'Hsinchu, Taiwan' 'Berneck']

In [16]:
print(comparar_columnas(df_gd, "gaTrackerData.locationId", "header.locId"))
print("")
print(df_gd["gaTrackerData.locationId"].unique())
print("")
print(df_gd["header.locId"].unique())

Las columnas 'gaTrackerData.locationId' y 'header.locId' son diferentes. Hay 18608 valores diferentes.

[3094484 3183562 2802090 ... 3508213 3050208 3295829]

[3094484 3183562 2802090 ... 3508213 3050208 3295829]

In [17]:
print(comparar_columnas(df_gd, "gaTrackerData.sector", "overview.sector"))
print("")
print(df_gd["gaTrackerData.sector"].unique())
print("")
print(df_gd["overview.sector"].unique())

Las columnas 'gaTrackerData.sector' y 'overview.sector' son diferentes. Hay 53458 valores diferentes.

['Finance' 'Biotech & Pharmaceuticals' nan 'Business Services'
 'Information Technology' 'Accounting & Legal' 'Manufacturing' 'Retail'
 'Telecommunications' 'Oil, Gas, Energy & Utilities' 'Non-Profit'
 'Transportation & Logistics' 'Government'
 'Construction, Repair & Maintenance' 'Insurance' 'Media' 'Education'
 'Aerospace & Defense' 'Health Care' 'Agriculture & Forestry'
 'Real Estate' 'Travel & Tourism' 'Arts, Entertainment & Recreation'
 'Consumer Services' 'Restaurants, Bars & Food Services' 'Mining & Metals']

['Finance' 'Biotech & Pharmaceuticals' nan 'Business Services'
 'Information Technology' 'Accounting & Legal' 'Manufacturing' 'Retail'
 'Telecommunications' 'Oil, Gas, Energy & Utilities' 'Non-Profits'
 'Transportation & Logistics' 'Government'
 'Building, Repair & Maintenance' 'Insurance' 'Media' 'Education'
 'Aerospace & Defence' 'Healthcare' 'Agriculture & Forestry' 'Property'
 'Travel & Tourism' 'Arts, Entertainment & Recreation' 'Consumer Services'
 'Restaurants, Pubs, Bars & Food Service' 'Mining & Metals']

In [18]:
print(comparar_columnas(df_gd, "gaTrackerData.sectorId", "overview.sectorId"))
print("")
print(df_gd["gaTrackerData.sectorId"].unique())
print("")
print(df_gd["overview.sectorId"].unique())

Las columnas 'gaTrackerData.sectorId' y 'overview.sectorId' son iguales.

[10010 10005     0 10006 10013 10001 10015 10022 10023 10019 10018 10024
 10011 10007 10014 10016 10009 10002 10012 10003 10020 10025 10004 10008
 10021 10017]

[10010 10005     0 10006 10013 10001 10015 10022 10023 10019 10018 10024
 10011 10007 10014 10016 10009 10002 10012 10003 10020 10025 10004 10008
 10021 10017]

In [19]:
print(comparar_columnas(df_gd, "header.rating", "rating.starRating"))
print("")
print(df_gd["header.rating"].unique())
print("")
print(df_gd["rating.starRating"].unique())

Las columnas 'header.rating' y 'rating.starRating' son diferentes. Hay 18391 valores diferentes.

[-0.1   3.8   2.4   1.5   3.5   3.3   4.    0.    3.9   4.6   3.    4.2
  3.7   4.1   4.4   3.6   2.8   5.    1.    2.5   3.4   4.5   2.6   2.9
  4.3   3.2   4.21  2.    4.7   3.1   2.1   4.9   2.7   2.3   3.19  2.2
  4.8   3.91  1.6   4.73  3.43  1.8   1.7   1.9   3.86  3.51  3.89  3.73
  3.58  4.03  3.56  3.98  3.71  3.83  3.29  3.13  4.97  3.72  3.45  3.46
  1.4   1.3   1.2   3.75  3.48  4.52  4.27  3.53  3.96  2.86  4.64  3.74
  3.62  3.39  3.44  3.38  4.29  3.76  3.57  3.35  3.65  4.06  3.32  4.19
  4.01  2.41  4.65  3.08  4.71  2.88  4.12  3.94  2.93  3.36  3.18  3.52
  4.08  4.26  4.45  4.09  3.92  3.24  4.39  3.81  3.84  3.77  2.82  2.96
  4.23  3.78  3.64  3.27  4.05  4.17  2.95  3.85  2.62  3.12  4.11  3.21
  3.15  4.13  3.25  3.82  3.02  4.16  4.49  4.78  3.33  3.37  3.47  2.29
  3.69  3.49  3.07  3.67  2.71  2.69  3.55  4.75  2.84  3.63  3.66  3.79
  2.61  4.84  2.85  3.88  4.91  3.93  4.02  4.28  2.66  4.15  4.07  4.94
  4.18  3.03  3.97  4.44  3.54  3.68  3.99  4.72  4.47  3.14  2.79  3.42
  4.54  2.98  3.59  3.06  4.48  3.09  3.95  3.34  2.91  3.11  4.04  4.37
  3.26  4.24  2.92  3.16  4.66  2.52  3.87  1.85  4.55]

[-0.1   3.8   2.4   1.5   3.5   3.3   4.     nan  3.9   4.6   3.    4.2
  3.7   4.1   4.4   3.6   2.8   5.    1.    2.5   3.4   4.5   2.6   2.9
  4.3   3.2   4.21  2.    4.7   3.1   2.1   4.9   2.7   2.3   3.19  2.2
  4.8   3.91  1.6   4.73  3.43  1.8   1.7   1.9   3.86  3.51  3.89  3.73
  3.58  4.03  3.56  3.98  3.71  3.83  3.29  3.13  4.97  0.    3.72  3.45
  3.46  1.4   1.3   1.2   3.75  3.48  4.52  4.27  3.53  3.96  2.86  4.64
  3.74  3.62  3.39  3.44  3.38  4.29  3.76  3.57  3.35  3.65  4.06  3.32
  4.19  4.01  2.41  4.65  3.08  4.71  2.88  4.12  3.94  2.93  3.36  3.18
  3.52  4.08  4.26  4.45  4.09  3.92  3.24  4.39  3.81  3.84  3.77  2.82
  2.96  4.23  3.78  3.64  3.27  4.05  4.17  2.95  3.85  2.62  3.12  4.11
  3.21  3.15  4.13  3.25  3.82  3.02  4.16  4.49  4.78  3.33  3.37  3.47
  2.29  3.69  3.49  3.07  3.67  2.71  2.69  3.55  4.75  2.84  3.63  3.66
  3.79  2.61  4.84  2.85  3.88  4.91  3.93  4.02  4.28  2.66  4.15  4.07
  4.94  4.18  3.03  3.97  4.44  3.54  3.68  3.99  4.72  4.47  3.14  2.79
  3.42  4.54  2.98  3.59  3.06  4.48  3.09  3.95  3.34  2.91  3.11  4.04
  4.37  3.26  4.24  2.92  3.16  4.66  2.52  3.87  1.85  4.55]

In [20]:
df_gd = unir_columnas_y_reemplazar_nulos(df_gd, "gaTrackerData.empId", "header.employerId", "company_id")
df_gd = unir_columnas_y_reemplazar_nulos(df_gd, "gaTrackerData.empName", "map.employerName", "company_n")
df_gd = unir_columnas_y_reemplazar_nulos(df_gd, "company_n", "header.employerName", "company_name")
df_gd = unir_columnas_y_reemplazar_nulos(df_gd, "overview.size", "gaTrackerData.empSize", "company_size")
df_gd = unir_columnas_y_reemplazar_nulos(df_gd, "gaTrackerData.expired", "header.expired", "job_expired")
df_gd = unir_columnas_y_reemplazar_nulos(df_gd, "gaTrackerData.industry", "overview.industry", "industry")
df_gd = unir_columnas(df_gd, "gaTrackerData.industryId", "overview.industryId", "industry_id")
df_gd = unir_columnas(df_gd, "gaTrackerData.jobTitle", "header.jobTitle", "job_title")
df_gd = unir_columnas(df_gd, "map.location", "header.location", "location")
df_gd = unir_columnas_y_reemplazar_nulos(df_gd, "gaTrackerData.locationId", "header.locId", "location_id")
df_gd = unir_columnas_y_reemplazar_nulos(df_gd, "gaTrackerData.sector", "overview.sector", "sector")
df_gd = unir_columnas(df_gd, "gaTrackerData.sectorId", "overview.sectorId", "sector_id")
df_gd = unir_columnas_y_reemplazar_nulos(df_gd, "header.rating", "rating.starRating", "company_rating")

In [21]:
df_gd.rename(columns={
        "header.posted": "date_posted",
        "header.payHigh": "pay_high",
        "header.payLow": "pay_low",
        "header.payMed": "pay_med",
        "header.payPeriod": "pay_period",
        "header.salaryHigh": "pay_salaryhigh",
        "job.description": "job_description",
        "job.jobSource": "job_source",
        "job.jobTitleId": "job_id",
        "map.country": "country",
        "map.lat": "latitude",
        "map.lng": "longitude",
        "map.address": "address",
        "map.postalCode": "postal_code",
        "overview.foundedYear": "company_founded",
        "overview.revenue": "company_revenue",
        "overview.competitors": "company_competitors",
        "salary.country.cc3LetterISO": "salary_ISO",
        "salary.country.currency.displayName": "salary_currency_name",
        "wwfu": "wwfu",
        "breadCrumbs": "bread_crumbs"
    }, inplace=True)

In [22]:
df_gd = df_gd[["job_id", "job_title", "job_description", "job_expired", "job_source", "date_posted",
               "pay_med", "pay_high", "pay_low", "pay_period", "pay_salaryhigh","salary_ISO", "salary_currency_name", 
               "location_id", "postal_code", "address", "location", "country", "latitude", "longitude", 
               "company_id", "company_name", "company_size",  "company_revenue", "company_founded", "company_rating", "company_competitors", 
               "industry_id", "industry", "sector_id", "sector", "wwfu", "bread_crumbs"]]

In [23]:
df_gd

,job_id,job_title,job_description,job_expired,job_source,date_posted,pay_med,pay_high,pay_low,pay_period,pay_salaryhigh,salary_ISO,salary_currency_name,location_id,postal_code,address,location,country,latitude,longitude,company_id,company_name,company_size,company_revenue,company_founded,company_rating,company_competitors,industry_id,industry,sector_id,sector,wwfu,bread_crumbs
0,-1,Biogas Project Development Manager,We are the drivers of the future who offer a g...,False,WorkableHR.com,"Oct 24, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3094484,NaN,NaN,Warsaw,Poland,52.2500,21.0000,2183810,Modus Group,501 to 1000 employees,Unknown / Non-Applicable,1993,-0.1,NaN,200053,Investment Banking & Asset Management,10010,Finance,NaN,2801
1,-1,Quality Manager - Boehringer Ingelheim Healthc...,<strong></strong>\n<br/><br/>\n<strong></stron...,False,taleo,"Nov 4, 2019",NaN,NaN,NaN,NaN,NaN,GBR,United Kingdom Pound (GBP),3183562,NaN,NaN,Porto,NaN,41.1500,-8.6167,10416,Boehringer Ingelheim,10000+ employees,£5 to £10 billion (GBP),1885,3.8,NaN,200021,Biotech & Pharmaceuticals,10005,Biotech & Pharmaceuticals,NaN,2802
2,-1,"Senior Software Engineer (PHP, Elixir, Python)",Dottori.it &egrave; il motore di ricerca che t...,False,Indeed XML Feed Employer,"Oct 28, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2802090,NaN,NaN,Milan,Italy,45.4667,9.2000,1043373,Immobiliare.it,201 to 500 employees,£25 to £50 million (GBP),0,2.4,NaN,0,NaN,0,NaN,NaN,2803
3,35043,Senior SQA Engineer,Codup is looking for a Senior SQA Engineer for...,False,Indeed XML Feed Dradis,"Nov 4, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3212296,NaN,NaN,Karāchi,PK,24.8667,67.0500,2226886,Codup,1 to 50 employees,Unknown / Non-Applicable,0,1.5,NaN,0,NaN,0,NaN,NaN,2804
4,33240,Research Manager,<strong>Department:</strong> Research &amp; Op...,False,Indeed XML Feed Employer,"Nov 1, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2940587,NaN,NaN,Bengaluru,IN,12.9670,77.5873,851555,Markelytics Solutions,201 to 500 employees,Unknown / Non-Applicable,2003,3.5,NaN,200028,Consulting,10006,Business Services,NaN,2805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165285,-1,East – Assistant Store Manager (All Brands),<strong>Responsibilities</strong>\n\n<ul>\n<li...,False,CustomCrawl,"Nov 6, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,Vietnam,NaN,0.0000,0.0000,414579,Valiram Group,1001 to 5000 employees,£2 to £5 billion (GBP),1935,2.0,NaN,200105,"Department, Clothing, & Shoe Stores",10022,Retail,NaN,58396
165286,-1,Data Center Partner Marketing Manager (Japan),<strong>Job Description</strong><br/><br/>Make...,False,Employer Feed,"Nov 10, 2019",NaN,NaN,NaN,NaN,NaN,GBR,United Kingdom Pound (GBP),2851580,NaN,NaN,Tokyo,JP,35.6850,139.7514,1519,Intel Corporation,10000+ employees,£5 to £10 billion (GBP),1968,4.0,NaN,200060,Computer Hardware & Software,10013,Information Technology,NaN,58397
165287,-1,Junior Production Manager m/v,Functie\n<br/>\nJe ondersteunt de productiever...,False,Indeed XML Feed Employer,"Oct 15, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2344926,NaN,NaN,Waregem,BE,50.8833,3.4167,1065492,Mc Three,Unknown,£100 to £500 million (GBP),1989,5.0,NaN,0,NaN,0,NaN,NaN,58398
165288,-1,Opleidingsmanager Industrieel Product Ontwerpen,Het Instituut voor Engineering is &eacute;&eac...,False,Indeed XML Feed Employer,"Oct 31, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3063595,NaN,NaN,Groningen,NL,53.2167,6.5500,595052,Hanzehogeschool Groningen,1001 to 5000 employees,£10 to £25 million (GBP),1986,3.9,NaN,200044,Colleges & Universities,10009,Education,NaN,58399
165289,-1,BIO MASS SCIENTIST / RESEARCHERS,"Responsible for the design, development and im...",False,Indeed XML Feed Employer,"Oct 14, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3235921,NaN,NaN,Singapore,SG,1.2931,103.8558,2962564,Tembusu Industries,Unknown,Unknown / Non-Applicable,0,-0.1,NaN,0,NaN,0,NaN,NaN,58400

---

#### ***NORMALIZAR LOS DATOS!***

In [25]:
# Convertir el dataset a minúsculas
df_gd = df_gd.applymap(lambda x: x.lower() if isinstance(x, str) else x)
df_gd

,job_id,job_title,job_description,job_expired,job_source,date_posted,pay_med,pay_high,pay_low,pay_period,pay_salaryhigh,salary_ISO,salary_currency_name,location_id,postal_code,address,location,country,latitude,longitude,company_id,company_name,company_size,company_revenue,company_founded,company_rating,company_competitors,industry_id,industry,sector_id,sector,wwfu,bread_crumbs
0,-1,biogas project development manager,we are the drivers of the future who offer a g...,False,workablehr.com,"oct 24, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3094484,NaN,NaN,warsaw,poland,52.2500,21.0000,2183810,modus group,501 to 1000 employees,unknown / non-applicable,1993,-0.1,NaN,200053,investment banking & asset management,10010,finance,NaN,2801
1,-1,quality manager - boehringer ingelheim healthc...,<strong></strong>\n<br/><br/>\n<strong></stron...,False,taleo,"nov 4, 2019",NaN,NaN,NaN,NaN,NaN,gbr,united kingdom pound (gbp),3183562,NaN,NaN,porto,NaN,41.1500,-8.6167,10416,boehringer ingelheim,10000+ employees,£5 to £10 billion (gbp),1885,3.8,NaN,200021,biotech & pharmaceuticals,10005,biotech & pharmaceuticals,NaN,2802
2,-1,"senior software engineer (php, elixir, python)",dottori.it &egrave; il motore di ricerca che t...,False,indeed xml feed employer,"oct 28, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2802090,NaN,NaN,milan,italy,45.4667,9.2000,1043373,immobiliare.it,201 to 500 employees,£25 to £50 million (gbp),0,2.4,NaN,0,NaN,0,NaN,NaN,2803
3,35043,senior sqa engineer,codup is looking for a senior sqa engineer for...,False,indeed xml feed dradis,"nov 4, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3212296,NaN,NaN,karāchi,pk,24.8667,67.0500,2226886,codup,1 to 50 employees,unknown / non-applicable,0,1.5,NaN,0,NaN,0,NaN,NaN,2804
4,33240,research manager,<strong>department:</strong> research &amp; op...,False,indeed xml feed employer,"nov 1, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2940587,NaN,NaN,bengaluru,in,12.9670,77.5873,851555,markelytics solutions,201 to 500 employees,unknown / non-applicable,2003,3.5,NaN,200028,consulting,10006,business services,NaN,2805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165285,-1,east – assistant store manager (all brands),<strong>responsibilities</strong>\n\n<ul>\n<li...,False,customcrawl,"nov 6, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1,NaN,NaN,vietnam,NaN,0.0000,0.0000,414579,valiram group,1001 to 5000 employees,£2 to £5 billion (gbp),1935,2.0,NaN,200105,"department, clothing, & shoe stores",10022,retail,NaN,58396
165286,-1,data center partner marketing manager (japan),<strong>job description</strong><br/><br/>make...,False,employer feed,"nov 10, 2019",NaN,NaN,NaN,NaN,NaN,gbr,united kingdom pound (gbp),2851580,NaN,NaN,tokyo,jp,35.6850,139.7514,1519,intel corporation,10000+ employees,£5 to £10 billion (gbp),1968,4.0,NaN,200060,computer hardware & software,10013,information technology,NaN,58397
165287,-1,junior production manager m/v,functie\n<br/>\nje ondersteunt de productiever...,False,indeed xml feed employer,"oct 15, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2344926,NaN,NaN,waregem,be,50.8833,3.4167,1065492,mc three,unknown,£100 to £500 million (gbp),1989,5.0,NaN,0,NaN,0,NaN,NaN,58398
165288,-1,opleidingsmanager industrieel product ontwerpen,het instituut voor engineering is &eacute;&eac...,False,indeed xml feed employer,"oct 31, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3063595,NaN,NaN,groningen,nl,53.2167,6.5500,595052,hanzehogeschool groningen,1001 to 5000 employees,£10 to £25 million (gbp),1986,3.9,NaN,200044,colleges & universities,10009,education,NaN,58399
165289,-1,bio mass scientist / researchers,"responsible for the design, development and im...",False,indeed xml feed employer,"oct 14, 2019",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3235921,NaN,NaN,singapore,sg,1.2931,103.8558,2962564,tembusu industries,unknown,unknown / non-applicable,0,-0.1,NaN,0,NaN,0,NaN,NaN,58400

In [30]:
df_job_title = df_gd[["job_title"]]
df_job_title

                                                job_title
0                      biogas project development manager
1       quality manager - boehringer ingelheim healthc...
2          senior software engineer (php, elixir, python)
3                                     senior sqa engineer
4                                        research manager
...                                                   ...
165285        east – assistant store manager (all brands)
165286      data center partner marketing manager (japan)
165287                      junior production manager m/v
165288    opleidingsmanager industrieel product ontwerpen
165289                   bio mass scientist / researchers

[165290 rows x 1 columns]

In [31]:
import re
import pandas as pd

# Patrones de nivel a buscar
jr_pattern = r'\b(jr|junior)\b'
mid_pattern = r'\b(mid|middle)\b'
sr_pattern = r'\b(sr|senior)\b'
ssr_pattern = r'\b(ssr|semi\s*senior)\b'

# Función para extraer el nivel de un título de trabajo
def extract_level(title):
    level = ''
    if re.search(jr_pattern, title, flags=re.IGNORECASE):
        level = 'Junior'
    elif re.search(mid_pattern, title, flags=re.IGNORECASE):
        level = 'Mid'
    elif re.search(sr_pattern, title, flags=re.IGNORECASE):
        level = 'Senior'
    elif re.search(ssr_pattern, title, flags=re.IGNORECASE):
        level = 'Semi Senior'
    return level

# Crear una nueva columna 'level' en el DataFrame
df_job_title['level'] = df_job_title['job_title'].apply(extract_level)
df_job_title

C:\Users\emida\AppData\Local\Temp\ipykernel_11876\1903692674.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_job_title['level'] = df_job_title['job_title'].apply(extract_level)

                                                job_title   level
0                      biogas project development manager
1       quality manager - boehringer ingelheim healthc...
2          senior software engineer (php, elixir, python)  Senior
3                                     senior sqa engineer  Senior
4                                        research manager
...                                                   ...     ...
165285        east – assistant store manager (all brands)
165286      data center partner marketing manager (japan)
165287                      junior production manager m/v  Junior
165288    opleidingsmanager industrieel product ontwerpen
165289                   bio mass scientist / researchers

[165290 rows x 2 columns]